require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'BotranExperience' do
  pod 'Firebase/AnalyticsWithoutAdIdSupport'
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  $RNFirebaseAsStaticFramework = true
  # Comment the next line if you don't want to use dynamic frameworks
  config = use_native_modules!
  # use_frameworks!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  pod 'ViroReact', :path => '../node_modules/@viro-community/react-viro/ios/'
  pod 'ViroKit', :path => '../node_modules/@viro-community/react-viro/ios/dist/ViroRenderer/'
  
  use_native_modules!
  pod 'react-native-idle-timer', :path => '../node_modules/react-native-idle-timer'

end

def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end

post_install do |installer|
        find_and_replace("./node_modules/react-native/React/Base/RCTKeyCommands.m",
                                "_modifierFlags",
                                "_modifierEventFlags")
        find_and_replace("./node_modules/react-native/React/Base/RCTKeyCommands.m",
                                "_modifiedInput",
                                "_modifiedEventInput")
        find_and_replace("./node_modules/react-native/React/Base/RCTKeyCommands.m",
                                "_isKeyDown",
                                "_isKeyEventDown")
        find_and_replace("./node_modules/react-native/React/DevSupport/RCTPackagerClient.h",
                                "handleNotification",
                                "handlePackageNotification")
        find_and_replace("./node_modules/react-native/React/DevSupport/RCTPackagerConnection.mm",
                                "handleNotification",
                                "handlePackageNotification")
end

