# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'BotranExperience' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"],
  # to enable hermes on iOS, change `false` to `true` and then install pods
  :hermes_enabled => false)
  pod 'ViroReact', :path => '../node_modules/@viro-community/react-viro/ios/'
  pod 'ViroKit', :path => '../node_modules/@viro-community/react-viro/ios/dist/ViroRenderer/'
  target 'BotranExperienceTests' do
    inherit! :search_paths
    # Pods for testing
  end
  use_native_modules!
end

target 'BotranExperience-tvOS' do
  target 'BotranExperience-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
